#!/bin/sh
set -e

ROOT_DIR=$(git rev-parse --show-toplevel)
cd "$ROOT_DIR"

case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        ./gradlew.bat spotlessCheck
        ;;
    *)
        ./gradlew spotlessCheck
        ;;
esac
